name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Prashant-Dwivedi-08-01/The-TradeBook-Backend@v2 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "the-trade-book" #Must be unique in Heroku
          heroku_email: "virtualtrading194@gmail.com"
